# Generated by Django 2.0.8 on 2019-07-06 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '模拟登陆用户表',
                'verbose_name_plural': '模拟登陆用户表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DocData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_dict', models.TextField()),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '文档数据表',
                'verbose_name_plural': '文档数据表',
                'ordering': ['-id'],
            },
        ),
    ]
